name: tcc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5

  flutter_bloc: ^7.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - images/
    - images/baseImages/
    - images/colorblindOnlyTests/
    - images/defaultPlates/
    - images/deuteranopiaPlates/
    - images/protanopiaPlates/
  uses-material-design: true
