name: tcc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.7

  flutter_svg: ^1.1.5

  flutter_bloc: ^7.0.0

  cupertino_icons: ^1.0.2

  json_serializable: ^6.1.5

  json_annotation: ^4.1.0

  build_runner: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - audios/
    - images/
    - images/baseImages/
    - images/colorblindOnlyTests/
    - images/defaultPlates/
    - images/deuteranopiaPlates/
    - images/protanopiaPlates/
    - images/everyoneSees/
    - images/generalIcons/
    - instructionsAssets/
    - instructionsAssets/gifs/
  uses-material-design: true
